services:
  - type: web
    name: laundry-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
```

## 2. Alternative: If using a different static host, create these files:

### For Netlify - Create `public/_redirects`:
```
/*    /index.html   200